/**:
    ros__parameters:
        robot_description: "ROBOT_DESC_PLACEHOLDER"
        robot_description_semantic: "SRDF_PLACEHOLDER"
        moveit_manage_controllers: false
        planning_pipelines: ["ompl"]
        default_planning_pipeline: ompl
        arm:
            kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
            kinematics_solver_search_resolution: 0.005
            kinematics_solver_timeout: 0.05
            kinematics_solver_attempts: 3
