<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypesns="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>fanuc_m20id25_support</name>
  <version>0.1.0</version>
  <description>FANUC M-20iD/25 kinematics and controller frame conventions.</description>
  <maintainer email="z@z.com">Zhang HaHa</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-scipy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
